### ISSUE TITLE
AttributeError: 'VisionTransformer' object has no attribute 'dist_token'

### ISSUE THREAD

**Issue by mmazuecos** [OPEN-AIR-SUN/Cerberus#2]
I've tried to evaluate your pretrained model following the [instructions](https://github.com/OPEN-AIR-SUN/Cerberus/blob/main/readme.md), but I'm stuck with the 'dist_token' not being an attribute of VisionTransformer

The environment has the following versions:

- python==3.6.13
- torch==1.8.1
- torchvision==0.9.1
- opencv-python==4.5.2
- timm==0.4.5
- CUDAtoolkit==11.1

Maybe I'm missing a file or a custom build?

Full traceback:
```
$ CUDA_VISIBLE_DEVICES=0 python main.py test -d dataset_path -s 512 --resume model_best.pth.tar --phase val --batch-size 1 --ms --workers 10 --classes 4
main.py test -d dataset_path -s 512 --resume model_best.pth.tar --phase val --batch-size 1 --ms --workers 10 --classes 4                                      
Namespace(cmd='test', data_dir='dataset_path', classes=4, crop_size=512, step=200, arch=None, batch_size=1, epochs=10, lr=0.01, lr_mode='step', momentum=0.9, 
weight_decay=0.0001, evaluate=False, resume='model_best.pth.tar', trans_resume='', pretrained='', pretrained_model='', workers=10, load_rel=None, phase='val',
 random_scale=0, random_rotate=0, bn_sync=False, ms=True, trans=False, with_gt=False, test_suffix='')                                                         
cmd : test                                                                                                                                                    
data_dir : dataset_path                                                                                                                                       
classes : 4                                                                                                                                                   
crop_size : 512                                                                
step : 200                                                                                                                                                    
arch : None                                                                                                                                                   
batch_size : 1                                                                                                                                                
epochs : 10                                                                                                                                                   
lr : 0.01                                                                                                                                                     
lr_mode : step                                                                                                                                                
momentum : 0.9                                                                                                                                                
weight_decay : 0.0001                                                          
evaluate : False                                                                                                                                              
resume : model_best.pth.tar                                                                                                                                   
trans_resume :                         
pretrained :                                                                                                                                                  
pretrained_model :                     
workers : 10                           
load_rel : None                                                                                                                                               
phase : val                                                                                                                                                   
random_scale : 0                       
random_rotate : 0                      
bn_sync : False                        
ms : True                              
trans : False                          
with_gt : False                        
test_suffix :
[W NNPACK.cpp:80] Could not initialize NNPACK! Reason: Unsupported hardware.                                                                                  
/users/mmazuecos/miniconda3/envs/cerberus/lib/python3.9/site-packages/torch/nn/functional.py:3454: UserWarning: Default upsampling behavior when mode=bilinear
 is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for det
ails.                                  
  warnings.warn(                       
Traceback (most recent call last):                                             
  File "/users/mmazuecos/Cerberus/main.py", line 1798, in <module>                                                                                            
    main()                             
  File "/users/mmazuecos/Cerberus/main.py", line 1794, in main                                                                                                
    test_seg_cerberus(args)                                                    
  File "/users/mmazuecos/Cerberus/main.py", line 1719, in test_seg_cerberus                                                                                   
    mAP = test_ms_cerberus(test_loader_list, model, save_vis=True,                                                                                            
  File "/users/mmazuecos/Cerberus/main.py", line 1491, in test_ms_cerberus                                                                                    
    final, _, _ = model(image_var, index)                                      
  File "/users/mmazuecos/miniconda3/envs/cerberus/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl                            
    result = self.forward(*input, **kwargs)                                                                                                                   
  File "/users/mmazuecos/Cerberus/model/models.py", line 379, in forward                                                                                      
    layer_1, layer_2, layer_3, layer_4 = forward_vit(self.pretrained, x)                                                                                      
  File "/users/mmazuecos/Cerberus/model/vit.py", line 109, in forward_vit                                                                                     
    glob = pretrained.model.forward_flex(x)                                                                                                                   
  File "/users/mmazuecos/Cerberus/model/vit.py", line 184, in forward_flex                                                                                    
    if self.dist_token:                                                        
  File "/users/mmazuecos/miniconda3/envs/cerberus/lib/python3.9/site-packages/torch/nn/modules/module.py", line 947, in __getattr__                           
    raise AttributeError("'{}' object has no attribute '{}'".format(
```

**Comment by Fromandto** [comment]
Xiaoxue says she has responded to your e-mail before ..?

**Comment by cxx226** [comment]
'VisionTransformer' is defined and implemented by timm, so I think this error is caused by the version of timm. Try 
`pip install --upgrade timm`
or 
`pip install timm==0.5.4`
which works in our environment. Hoping this would be helpful for you.

**Comment by mmazuecos** [comment]
Hi everyone
The problem was the timm version indeed. Upgrading to 0.5.4 solved the issue. May I suggest to update the README.md to say it requires timm==0.5.4? (Currently it says it need timm==0.4.5). 

Thanks a lot for the help
